// Rust / rustls TLS configuration template.
//
// rustls (https://github.com/rustls/rustls) is a memory-safe TLS
// implementation written in Rust. As of rustls 0.23.18 (with the
// `aws-lc-rs` provider), rustls negotiates the X25519MLKEM768 hybrid PQ
// group automatically when both peers support it; SecP256r1MLKEM768 and
// SecP384r1MLKEM1024 are not yet exposed.
//
// Rust applications that link against the `openssl` crate (rather than
// rustls) inherit the system openssl.cnf and therefore pick up the
// `Groups` / `CipherString` / `Ciphersuites` directives generated by the
// "OpenSSL config (openssl.cnf)" target in this tool.
//
// References (see src/static/citations.bib):
//  - rustls release notes:        https://github.com/rustls/rustls/releases
//  - rustls PQ key exchange:      https://github.com/rustls/rustls/issues/1936
//  - draft-kwiatkowski-tls-ecdhe-mlkem
import { safe } from './ctx.js';

export default (form, output) => {
  const protocols = output.protocols;
  const supportsTls12 = protocols.includes('TLSv1.2');
  const supportsTls13 = protocols.includes('TLSv1.3');

  // Per-template context (see ./ctx.js): every form.* value spliced
  // into the rendered config string is filtered through safe() as
  // defence in depth.
  const ctx = {
    config: safe(form.config),
  };

  let conf =
      '// '+output.header+'\n'+
      '// '+output.link+'\n'+
      '//\n'+
      '// Cargo.toml:\n'+
      '//     [dependencies]\n'+
      '//     rustls = { version = "0.23", features = ["aws-lc-rs"] }\n'+
      '//     rustls-pemfile = "2"\n'+
      '//\n'+
      '// rustls negotiates X25519MLKEM768 (hybrid PQ) automatically with\n'+
      '// the aws-lc-rs provider when both peers support it. Curve / cipher\n'+
      '// preference lists are not user-configurable in rustls; they are\n'+
      '// picked by the chosen CryptoProvider. This template selects only\n'+
      '// the protocol versions and certificate material.\n'+
      '\n'+
      'use std::fs::File;\n'+
      'use std::io::BufReader;\n'+
      'use std::sync::Arc;\n'+
      '\n'+
      'use rustls::{ServerConfig, version};\n'+
      'use rustls::crypto::aws_lc_rs::default_provider;\n'+
      'use rustls_pemfile::{certs, pkcs8_private_keys};\n'+
      '\n'+
      'fn load_certs(path: &str) -> Vec<rustls::pki_types::CertificateDer<\'static>> {\n'+
      '    let mut reader = BufReader::new(File::open(path).expect("cert file"));\n'+
      '    certs(&mut reader).filter_map(Result::ok).collect()\n'+
      '}\n'+
      '\n'+
      'fn load_key(path: &str) -> rustls::pki_types::PrivateKeyDer<\'static> {\n'+
      '    let mut reader = BufReader::new(File::open(path).expect("key file"));\n'+
      '    let mut keys: Vec<_> = pkcs8_private_keys(&mut reader).filter_map(Result::ok).collect();\n'+
      '    rustls::pki_types::PrivateKeyDer::Pkcs8(keys.remove(0))\n'+
      '}\n'+
      '\n'+
      'fn main() {\n'+
      '    // '+ctx.config+' configuration\n'+
      '    let provider = Arc::new(default_provider());\n'+
      '    let versions: &[&\'static rustls::SupportedProtocolVersion] = &[\n';

  if (supportsTls13) {
    conf += '        &version::TLS13,\n';
  }
  if (supportsTls12) {
    conf += '        &version::TLS12,\n';
  }

  conf +=
      '    ];\n'+
      '\n'+
      '    let certs = load_certs("/path/to/signed_cert_plus_intermediates");\n'+
      '    let key = load_key("/path/to/private_key");\n'+
      '\n'+
      '    let config = ServerConfig::builder_with_provider(provider)\n'+
      '        .with_protocol_versions(versions)\n'+
      '        .expect("inconsistent protocol versions")\n'+
      '        .with_no_client_auth()\n'+
      '        .with_single_cert(certs, key)\n'+
      '        .expect("bad cert/key");\n'+
      '\n'+
      '    let _config = Arc::new(config);\n';

  if (form.hsts) {
    conf +=
      '\n'+
      '    // When wrapping rustls in an HTTP server (e.g. hyper, axum),\n'+
      '    // emit the HSTS response header on TLS responses:\n'+
      '    //     Strict-Transport-Security: max-age='+output.hstsMaxAge+'; includeSubDomains\n';
  }

  conf +=
      '\n'+
      '    // Bind your TCP listener to :443 and feed accepted streams\n'+
      '    // into rustls::ServerConnection / tokio_rustls::TlsAcceptor\n'+
      '    // (depending on your runtime) using `_config`.\n'+
      '}\n';

  return conf;
};
